export const initState = {
  permukaanGigi: {
    M: 0,
    O: 0,
    D: 0,
    V: 0,
    L: 0,
  },
  keadaanGigi: {
    SOU: 1,
    NON: 0,
    UNE: 0,
    PRE: 0,
    IMV: 0,
    ANO: 0,
    DIA: 0,
    ATT: 0,
    ABR: 0,
    CFR: 0,
    NVT: 0,
    RRX: 0,
    MIS: 0,
    CAR: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
  },
  bahanRestorasi: {
    AMF: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
    GIF: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
    COF: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
    FIS: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
    INL: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
    ONL: { center: 0, top: 0, bottom: 0, left: 0, right: 0 },
  },
  restorasi: {
    FMC: 0,
    POC: 0,
    MPC: 0,
    GMC: 0,
    RCT: 0,
    IPX: 0,
    MEB: 0,
    POB: 0,
    PON: 0,
    ABU: 0,
  },
  protesa: {
    PRD: 0,
    FLD: 0,
    ACR: 0,
  },
};
